version: 2
updates:
  - package-ecosystem:  "github-actions"
    directory: "/"
    schedule:
        interval: "daily"
    rebase-strategy: "auto"
    target-branch: "dev"
    labels:
      - "dependabot"

  - package-ecosystem: "pip"
    directory: "/wiki/requirements.txt"
    schedule:
        interval: "daily"
    rebase-strategy: "auto"
    target-branch: "dev"
    labels:
      - "dependabot"

  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: "daily"
    rebase-strategy: "auto"
    target-branch: "dev"
    labels:
      - "dependabot"
