version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
        interval: "daily"
    rebase-strategy: "auto"
    target-branch: "dev"
    labels:
      - "dependabot"
    commit-message:
      prefix: "Github-actions updates"
      prefix-development: "Github-Actions dev"
      include: "scope"

  - package-ecosystem: "pip"
    directory: "/wiki/requirements.txt"
    schedule:
        interval: "daily"
    rebase-strategy: "auto"
    target-branch: "dev"
    labels:
      - "dependabot"
    commit-message:
      prefix: "pip depending updates"
      prefix-development: "pip dev"
      include: "scope"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    rebase-strategy: "auto"
    target-branch: "dev"
    labels:
      - "dependabot"
    commit-message:
      prefix: "Dockfile updates"
      prefix-development: "Dockfile dev"
      include: "scope"
