---
version: "3"
services:
  cloudflared:
    image: "cloudflare/cloudflared:2021.10.5-amd64"
    hostname: "cloudflared"
    container_name: "cloudflared"
    command: "'tunnel' 'run' '${CLOUDFLARED_UUID}'"
    networks:
      - proxy
    environment:
      - "PGID=${ID}"
      - "PUID=${ID}"
      - "TZ=${TZ}"
    volumes:
      - "${APPFOLDER}/cloudflared:/home/nonroot/.cloudflared"
    restart: always
networks:
  proxy:
    driver: bridge
    external: true
#"
