---
version: "3"
services:
  uploader:
    cap_add:
      - "SYS_ADMIN"
    container_name: "uploader"
    hostname: "uploader"
    environment:
      - "PGID=${ID}"
      - "PUID=${ID}"
      - "TZ=${TZ}"
    image: "ghcr.io/dockserver/docker-uploader:dockserver"
    restart: "${RESTARTAPP}"
    networks:
      - ${DOCKERNETWORK}
    security_opt:
      - "apparmor:unconfined"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "${APPFOLDER}/system:/system:rshared"
      - "unionfs:/mnt"
    labels:
      - "traefik.docker.network=proxy"
      - "dockupdater.enable=true"
 
networks:
  proxy:
    driver: bridge
    external: true
volumes:
  unionfs:
    driver: local-persist
    driver_opts:
      mountpoint: /mnt
