---
version: '3'
services:
  kasmweb:
    hostname: 'kasmweb'
    container_name: 'kasmweb'
    environment:
      - 'PGID=${ID}'
      - 'PUID=${ID}'
      - 'TZ=${TZ}'
      - 'UMASK=${UMASK}'
      - 'VNC_PW=${KASMPW}'
    image: 'kasmweb/desktop-deluxe:1.9.0'
    restart: '${RESTARTAPP}'
    shm_size: '512m'
    networks:
      - proxy
    security_opt:
      - 'no-new-privileges:true'
    volumes:
      - '${APPFOLDER}/kasmweb:/share:rw'
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=proxy'
      - 'dockupdater.enable=true'
      - 'traefik.http.routers.kasmweb-rtr.entrypoints=https'
      - 'traefik.http.routers.kasmweb-rtr.rule=Host(`kasmweb.${DOMAIN}`)'
      - 'traefik.http.routers.kasmweb-rtr.tls=true'
      - 'traefik.http.routers.kasmweb-rtr.tls.certresolver=dns-cloudflare'
      - 'traefik.http.routers.kasmweb-rtr.middlewares=chain-authelia@file'
      - 'traefik.http.routers.kasmweb-rtr.service=kasmweb-svc'
      - 'traefik.http.services.kasmweb-svc.loadbalancer.server.scheme=https'
      - 'traefik.http.services.kasmweb-svc.loadbalancer.server.port=6901'
networks:
  proxy:
    driver: bridge
    external: true