---
version: '3'
services:  
  unbound:
    image: ghcr.io/crazy-max/unbound
    hostname: unbound
    container_name: unbound
    ports:
      - ${PORTBLOCK}:5053:5053 #Donot expose this publically on a remote server only use VPN
      - ${PORTBLOCK}:5053:5053/udp #Donot expose this publically on a remote server only use VPN
    networks:
      - proxy
    environment:
      - 'PGID=${ID}'
      - 'PUID=${ID}'
      - 'TZ=${TZ}'
    restart: unless-stopped
    volumes:
      - ${APPFOLDER}/unbound:/config:ro
networks:
  proxy:
    driver: bridge
    external: true
