---
version: "3"
services:
  dockserver:
    hostname: "dockserver"
    container_name: "dockserver"
    environment:
      - "PGID=${ID}"
      - "PUID=${ID}"
    image: "dockserver/update:latest"
    restart: "${RESTARTAPP}"
    networks:
      - ${DOCKERNETWORK}
    security_opt:
      - "${SECURITYOPS}:${SECURITYOPSSET}"
    volumes:
      - "/opt/dockserver:/opt/dockserver"
    labels:
      - "traefik.docker.network=proxy"
      - "dockupdater.enable=true"
networks:
  proxy:
    driver: bridge
    external: true
