version: "2.1"
services:
  amd:
    image: randomninjaatk/amd:latest
    container_name: amd
    volumes:
      - '${APPFOLDER}/amd:/config:rw'
      - '${APPFOLDER}/amd/downloads-amd:/downloads-amd:rw'
      - 'unionfs:/mnt'
    environment:
      - 'PGID=${ID}'
      - 'PUID=${ID}'
      - AUTOSTART=true
      - SCRIPTINTERVAL=1h
      - DOWNLOADMODE=wanted
      - FALLBACKSEARCH=True
      - LIST=both
      - SearchType=both
      - Concurrency=1
      - EMBEDDED_COVER_QUALITY=80
      - FORMAT=FLAC
      - BITRATE=320
      - ENABLEPOSTPROCESSING=true
      - FORCECONVERT=false
      - requirequality=false
      - MatchDistance=10
      - replaygain=true
      - FolderPermissions=766
      - FilePermissions=666
      - 'MBRAINZMIRROR=${AMDMBRAINZMIRROR=}'
      - MBRATELIMIT=1
      - 'LidarrUrl=${AMDLidarrUrl}'
      - 'LidarrAPIkey=${AMDLidarrAPIkey}'
      - 'ARL_TOKEN=${AMDARL_TOKEN}'
      - NOTIFYPLEX=true
      - 'PLEXLIBRARYNAME=${AMDPLEXLIBRARYNAME}'
      - 'PLEXURL=${AMDPLEXURL}'
      - 'PLEXTOKEN=${AMDPLEXTOKEN}'
      - ALBUM_TYPE_FILTER=COMPILE
      - POSTPROCESSTHREADS=1
    labels:
      - 'dockupdater.enable=true'
    restart: '${RESTARTAPP}'
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
    external: true
volumes:
  unionfs:
    driver: local-persist
    driver_opts:
      mountpoint: /mnt
