---
version: '3'
services:
  bazarr4k:
    hostname: 'bazarr4k'
    container_name: 'bazarr4k'
    environment:
      - 'PGID=${ID}'
      - 'PUID=${ID}'
      - 'TZ=${TZ}'
      - 'UMASK=022'
      - 'DOCKER_MODS=ghcr.io/gilbn/theme.park:bazarr'
      - 'TP_ADDON=bazarr-4k-logo'
    image: 'ghcr.io/linuxserver/bazarr:latest'
    restart: 'unless-stopped'
    ports:
      - '127.0.0.1:6768:6767'
    networks:
      - proxy
    security_opt:
      - 'no-new-privileges:true'
    volumes:
      - '/opt/appdata/bazarr4k:/config:rw'
      - 'unionfs:/mnt'
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=proxy'
      - 'dockupdater.enable=true'
      - 'traefik.http.routers.bazarr4k-rtr.entrypoints=https'
      - 'traefik.http.routers.bazarr4k-rtr.rule=Host(`bazarr4k.${DOMAIN}`)'
      - 'traefik.http.routers.bazarr4k-rtr.tls=true'
      - 'traefik.http.routers.bazarr4k-rtr.tls.certresolver=dns-cloudflare'
      - 'traefik.http.routers.bazarr4k-rtr.middlewares=chain-authelia@file'
      - 'traefik.http.routers.bazarr4k-rtr.service=bazarr-svc'
      - 'traefik.http.services.bazarr4k-svc.loadbalancer.server.port=6767'
networks:
  proxy:
    driver: bridge
    external: true
volumes:
  unionfs:
    driver: local-persist
    driver_opts:
      mountpoint: /mnt