---
version: "3"
services:
  backup:
    hostname: "backup"
    container_name: "backup"
    environment:
      - "PGID=${ID}"
      - "PUID=${ID}"
      - "TZ=${TZ}"
      - "CONTAINER_TIMEZONE=${TZ}"
      - "BACKUP_HOLD=15"
      - "SERVER_ID=NOT-SET"
      - "RSYNC_COMPRESS_LEVEL=2"
      - "SET_CONTAINER_TIMEZONE=true"
    image: "ghcr.io/dockserver/docker-rsync-backup:latest"
    restart: "${RESTARTAPP}"
    labels:
      - "dockupdater.enable=true"
    networks:
      - ${DOCKERNETWORK}
    volumes:
      - "${APPFOLDER}:/home"
      - "/opt/backup:/backup"
      - "/etc/locatime:/etc/localtime:ro"
networks:
  proxy:
    driver: bridge
    external: true
