---
version: '3'
services:
  backup:
    hostname: 'backup'
    container_name: 'backup'
    environment:
      - 'PGID=${ID}'
      - 'PUID=${ID}'
      - 'TZ=${TZ}'
      - 'CRON_TIME=CRON_TIME'
      - 'CONTAINER_TIMEZONE=${TZ}'
      - 'BACKUP_HOLD=15'
      - 'SERVER_ID=SERVER_ID'
      - 'RSYNC_COMPRESS_LEVEL=2'
      - 'SET_CONTAINER_TIMEZONE=true'
    image: 'ghcr.io/dockserver/docker-rsync-backup:latest'
    restart: '${RESTARTAPP}'
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=proxy'
      - 'dockupdater.enable=true'
    networks:
      - proxy
    volumes:
      - '${APPFOLDER}/backup:/config:rw'
      - '${APPFOLDER}/:/home'
      - '/opt/backup:/backup'
      - '/etc/locatime:/etc/localtime:ro'
networks:
  proxy:
    driver: bridge
    external: true
