---
version: '3'
services:
  duplicati:
    hostname: 'duplicati'
    container_name: 'duplicati'
    environment:
      - 'PGID=${ID}'
      - 'PUID=${ID}'
      - 'TZ=${TZ}'
      - 'UMASK=${UMASK}'
    image: 'ghcr.io/linuxserver/duplicati'
    restart: '${RESTARTAPP}'
    networks:
      - proxy
    security_opt:
      - 'no-new-privileges:true'
    volumes:
      - '${APPFOLDER}/duplicati:/config:rw'
      - './:/source:rw'
networks:
  proxy:
    driver: bridge
    external: true
