---
version: '3'
services:
  instaloader:
    container_name: 'instaloader'
    hostname: 'instaloader'
    image: 'didc/docker-instaloader:latest'
    restart: '${RESTARTAPP}'
    networks:
      - proxy
    security_opt:
      - 'no-new-privileges:true'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - '${APPFOLDER}/instaloader/il_args.txt:/il_args.txt:rw'
      - '${APPFOLDER}/instaloader/il_targets.txt:/il_targets.txt:rw'
      - '${APPFOLDER}/instaloader/session-username:/session-username:rw'
      - '/var/run/docker.sock:/var/run/docker.sock'
    labels:
      - 'dockupdater.disable=true'
networks:
  proxy:
    driver: bridge
    external: true
