---
version: '3'
services:
  instaloader:
    container_name: 'instaloader'
    hostname: 'instaloader'
    image: 'didc/docker-instaloader:latest'
    restart: '${RESTARTAPP}'
    environment:
      - 'PGID=${ID}'
      - 'PUID=${ID}'
      - 'TZ=${TZ}'
    networks:
      - proxy
    security_opt:
      - 'no-new-privileges:true'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - '${APPFOLDER}/instaloader/il_args.txt:/il_args.txt:rw'
      - '${APPFOLDER}/instaloader/il_targets.txt:/il_targets.txt:rw'
      - '${APPFOLDER}/instaloader/session-username:/session-username:rw'
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=proxy'
      - 'dockupdater.enable=true'
networks:
  proxy:
    driver: bridge
    external: true
