---
version: '3'
services:
  mariadb:
    container_name: 'mariadb'
    hostname: 'mariadb'
    environment:
      - 'PGID=${ID}'
      - 'PUID=${ID}'
      - 'TZ=${TZ}'
      - 'UMASK=${UMASK}'
      - 'MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}'
    image: 'mariadb:latest'
    restart: '${RESTARTAPP}'
    ports:
      - '${PORTBLOCK}:3306:3306'
    networks:
      - proxy
    security_opt:
      - 'no-new-privileges:true'
    volumes:
      - '${APPFOLDER}/mariadb:/var/lib/mysql:rw'
    labels:
      - 'dockupdater.enable=true'
networks:
  proxy:
    driver: bridge
    external: true
