name: automerge
on:
  pull_request_target:
    types:
      - labeled
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.15.2"
        env:
          GITHUB_TOKEN: "${{ secrets.CR_PAT }}"
          MERGE_LABELS: "dependabot"          
          MERGE_COMMIT_MESSAGE: "pull_request_title"
          MERGE_FORKS: "false"
