name: Generate changelog
on:
  release:
    types: [created, edited]
  push:
    branches: 
      - master

jobs:
  generate-changelog-wiki:
    needs: generate-changelog
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: BobAnkh/auto-generate-changelog@master
      with:
        ACCESS_TOKEN: ${{secrets.CR_PAT}}
        PATH: '/wiki/docs/install/changelog.md'
        COMMIT_MESSAGE: 'docs(CHANGELOG): update release notes'
        TYPE: 'feat:Feature,fix:Bug Fixes,docs:Documentation,refactor:Refactor,perf:Performance Improvements'
