---
name: Run CLI
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Dockserver Wiki on GitHub Pages
    runs-on: ubuntu-latest
    if: github.event.repository.fork == false
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: '1'
          token: ${{ secrets.CR_PAT }}

      - name: Set up Python
        uses: actions/setup-python@v4.0.0
        with:
          python-version: '3.x'
          architecture: 'x64'

      - uses: actions/cache@v3
        with:
          key: ${{ github.ref }}
          path: .cache

      - name: Set up Wiki
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install --upgrade --force-reinstall -r wiki/requirements.txt
          mkdocs gh-deploy --force --config-file wiki/mkdocs.yml --remote-branch wiki
