name: Deploy docs to GitHub Pages via mkdocs
on:
  push:
    branches:
      - master
jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
    - name: Copycat
      uses: andstor/copycat-action@v3
      with:
        personal_token: ${{ secrets.CR_PAT }}
        src_path: README.md
        dst_path: /wiki/docs/index.md
        dst_owner: dockserver
        dst_branch: master
        src_branch: master
        username: nutsbot

  deploy:
    name: Deploy Wiki on Github Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install mkdocs
          python3 -m pip install mkdocs-material
          python3 -m pip install mkdocs-minify-plugin
          python3 -m pip install pip install mkdocs-redirects
      - run: pip install -r wiki/requirements.txt
      - run: mkdocs gh-deploy --force --config-file wiki/mkdocs.yml --remote-branch wiki
