name: Deploy docs to GitHub Pages via mkdocs
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  copy:
    name: Copy new Read.me
    runs-on: ubuntu-latest
    steps:
    - name: Copycat
      uses: andstor/copycat-action@v3
      with:
        personal_token: ${{ secrets.CR_PAT }}
        src_path: README.md
        dst_path: /wiki/docs/index.md
        dst_owner: dockserver
        dst_repo_name: dockserver
        dst_branch: master
        src_branch: master
        username: nutsbot

  deploy:
    needs: copy
    name: Deploy Wiki on Github Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.x
      - run: python3 -m pip install --upgrade pip
      - run: python3 -m pip install -r wiki/requirements.txt
      - run: mkdocs gh-deploy --force --config-file wiki/mkdocs.yml --remote-branch wiki

  Create_GitHub_release:
    needs: [copy,deploy]
    name: Create GitHub release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Create release for ${{ github.event.client_payload.ReleaseBranchName }}
        uses: actions/create-release@v1.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.CR_PAT }}
        with:
          tag_name: ${{ github.event.client_payload.ReleaseBranchName }}
          release_name: ${{ github.event.client_payload.ReleaseTitle }}
          body: ${{ github.event.client_payload.ReleaseBody }}
          prerelease: ${{ github.event.client_payload.Prerelease }}
