name: New Release

on:
  schedule:
    - cron: '* 1 * * 0'
  workflow_dispatch:

jobs:
  wiki:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - run: git checkout HEAD^
        
    - uses: BobAnkh/auto-generate-changelog@master
      with:
        ACCESS_TOKEN: ${{secrets.CR_PAT}}
        PATH: '/wiki/docs/install/changelog.md'
        COMMIT_MESSAGE: '#fix docs(CHANGELOG): update release notes'
        TYPE: 'feat:Feature,fix:Bug Fixes,docs:Documentation,refactor:Refactor,perf:Performance Improvements'


  build:
    name: Generate new tag
    needs: wiki
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2.4.0

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.36.0
        with:
          body: ${{steps.github_release.outputs.changelog}}
        env:
          GITHUB_TOKEN: ${{ secrets.CR_PAT }}
          WITH_V: true
          RELEASE_BRANCHES: master
          VERBOSE: true
