name: Continuous Integration

on:
  pull_request:
    branches: [master]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: ${{ github.head_ref }}
        persist-credentials: false

    - name: Prettify code
      uses: creyD/prettier_action@v4.0
      with:
        prettier_options: --write **/*.{json,yaml,md}
        only_changed: True
        github_token: ${{ secrets.CR_PAT }}
