name: revase

on:
  workflow_dispatch:
  push:
    branches:
    - master

jobs:
  rebase:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: peter-evans/rebase@v2
        with:
          base: master
