name: Upstreams

on:
  schedule:
    - cron: '* 1 * * 0'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update README with recent activity

    steps:
      - uses: actions/checkout@v2
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.CR_PAT }}
        with:
          COMMIT_MSG: '#fix'
          MAX_LINES: 10
